version: '1.0'

services:
  app:
    build: ./
    command: python main.py
    volumes:
      - .:/usr/src/app/
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kanalservis
    ports:
      - 5432:5432

volumes:
  postgres_data: